update(deps): typescript 3.7 and necessary prettier (#537)
New typescript requires the new prettier release.

Also converted a few instances in the code base to use the new typescript
language features.

Styled components also needed any update otherwise we get the following type errors:

```
01:16:02 typescript | frontend/src/components/CalendarDay.tsx(82,5): error TS2345: Argument of type '(p: ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>) => false | FlattenInterpolation<...>' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>'.
01:16:02 typescript |   Type '(p: ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>) => false | FlattenInterpolation<...>' is not assignable to type 'InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>'.
01:16:02 typescript |     Type 'false | FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>'.
01:16:02 typescript |       Type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>'.
01:16:02 typescript |         Type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to type 'FlattenInterpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>'.
01:16:02 typescript |           Types of property 'concat' are incompatible.
01:16:02 typescript |             Type '{ (...items: ConcatArray<Interpolation<ThemeProps<ITheme>>>[]): Interpolation<ThemeProps<ITheme>>[]; (...items: (string | ... 10 more ... | undefined)[]): Interpolation<...>[]; }' is not assignable to type '{ (...items: ConcatArray<Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>>[]): Interpolation<...>[]; (...items: (string | ... 10 more ... | undefined)[]): Inte...'.
01:16:02 typescript |               Types of parameters 'items' and 'items' are incompatible.
01:16:02 typescript |                 Type 'ConcatArray<Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>>' is not assignable to type 'ConcatArray<Interpolation<ThemeProps<ITheme>>>'.
01:16:02 typescript |                   Type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:02 typescript |                     Type 'FlattenInterpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:02 typescript |                       Type 'FlattenInterpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>' is not assignable to type 'FlattenInterpolation<ThemeProps<ITheme>>'.
01:16:02 typescript |                         The types returned by 'concat(...)' are incompatible between these types.
01:16:02 typescript |                           Type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>[]' is not assignable to type 'Interpolation<ThemeProps<ITheme>>[]'.
01:16:03 typescript |                             Type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                               Type 'FlattenInterpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dir" | "slot" | "style" | ... 248 more ... | "key"> & { ...; } & ICalendarDayContainerProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript | frontend/src/components/CalendarDay.tsx(83,5): error TS7006: Parameter 'p' implicitly has an 'any' type.
01:16:03 typescript | frontend/src/components/CalendarDay.tsx(84,5): error TS7006: Parameter 'p' implicitly has an 'any' type.
01:16:03 typescript | frontend/src/components/CalendarDay.tsx(88,26): error TS7006: Parameter 'p' implicitly has an 'any' type.
01:16:03 typescript | frontend/src/components/CalendarDay.tsx(93,24): error TS7006: Parameter 'p' implicitly has an 'any' type.
01:16:03 typescript | frontend/src/components/RecipeTitleDropdown.tsx(59,5): error TS2769: No overload matches this call.
01:16:03 typescript |   Overload 1 of 3, '(first: CSSObject | TemplateStringsArray | InterpolationFunction<ThemedStyledProps<ILinkProps, ITheme>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.
01:16:03 typescript |     Argument of type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<ILinkProps, ITheme>>'.
01:16:03 typescript |       Type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to type 'FlattenInterpolation<ThemedStyledProps<ILinkProps, ITheme>>'.
01:16:03 typescript |         Types of property 'concat' are incompatible.
01:16:03 typescript |           Type '{ (...items: ConcatArray<Interpolation<ThemeProps<ITheme>>>[]): Interpolation<ThemeProps<ITheme>>[]; (...items: (string | ... 10 more ... | undefined)[]): Interpolation<...>[]; }' is not assignable to type '{ (...items: ConcatArray<Interpolation<ThemedStyledProps<ILinkProps, ITheme>>>[]): Interpolation<ThemedStyledProps<ILinkProps, ITheme>>[]; (...items: (string | ... 10 more ... | undefined)[]): Interpolation<...>[]; }'.
01:16:03 typescript |             Types of parameters 'items' and 'items' are incompatible.
01:16:03 typescript |               Type 'ConcatArray<Interpolation<ThemedStyledProps<ILinkProps, ITheme>>>' is not assignable to type 'ConcatArray<Interpolation<ThemeProps<ITheme>>>'.
01:16:03 typescript |                 Type 'Interpolation<ThemedStyledProps<ILinkProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                   Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                     Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps, ITheme>>' is not assignable to type 'FlattenInterpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                       The types returned by 'concat(...)' are incompatible between these types.
01:16:03 typescript |                         Type 'Interpolation<ThemedStyledProps<ILinkProps, ITheme>>[]' is not assignable to type 'Interpolation<ThemeProps<ITheme>>[]'.
01:16:03 typescript |                           Type 'Interpolation<ThemedStyledProps<ILinkProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                             Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |   Overload 2 of 3, '(first: CSSObject | TemplateStringsArray | InterpolationFunction<ThemedStyledProps<ILinkProps & object, ITheme>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.
01:16:03 typescript |     Argument of type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>'.
01:16:03 typescript |       Type 'FlattenInterpolation<ThemeProps<ITheme>>' is not assignable to type 'FlattenInterpolation<ThemedStyledProps<ILinkProps & object, ITheme>>'.
01:16:03 typescript |         Types of property 'concat' are incompatible.
01:16:03 typescript |           Type '{ (...items: ConcatArray<Interpolation<ThemeProps<ITheme>>>[]): Interpolation<ThemeProps<ITheme>>[]; (...items: (string | ... 10 more ... | undefined)[]): Interpolation<...>[]; }' is not assignable to type '{ (...items: ConcatArray<Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>>[]): Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>[]; (...items: (string | ... 10 more ... | undefined)[]): Interpolation<...>[]; }'.
01:16:03 typescript |             Types of parameters 'items' and 'items' are incompatible.
01:16:03 typescript |               Type 'ConcatArray<Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>>' is not assignable to type 'ConcatArray<Interpolation<ThemeProps<ITheme>>>'.
01:16:03 typescript |                 Type 'Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                   Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps & object, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                     Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps & object, ITheme>>' is not assignable to type 'FlattenInterpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                       The types returned by 'concat(...)' are incompatible between these types.
01:16:03 typescript |                         Type 'Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>[]' is not assignable to type 'Interpolation<ThemeProps<ITheme>>[]'.
01:16:03 typescript |                           Type 'Interpolation<ThemedStyledProps<ILinkProps & object, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
01:16:03 typescript |                             Type 'FlattenInterpolation<ThemedStyledProps<ILinkProps & object, ITheme>>' is not assignable to type 'Interpolation<ThemeProps<ITheme>>'.
```