fix(api): gunicorn issue (#845)
We were getting an error before from gunicorn:

```

Error: module 'inspect' has no attribute 'getargspec'
```

also got the following error from nginx since the Django container wasn't starting:

```
2022/10/26 23:09:33 [emerg] 1#1: host not found in upstream "django" in /etc/nginx/conf.d/nginx.conf:148
nginx: [emerg] host not found in upstream "django" in /etc/nginx/conf.d/nginx.conf:148
```


We were on a 2017 version of gunicorn: https://pypi.org/project/gunicorn/19.7.1/

The gunicorn issue: https://github.com/benoitc/gunicorn/issues/1515