fix: n+1 serializer mixin type error (#556)
Turns out the wrappers passed to connection.execute_wrappers are expected
to call the `execute` arg and return its value.

https://docs.djangoproject.com/en/dev/topics/db/instrumentation/#connection-execute-wrapper

We were returning None and this resulted in some strange errors with django.

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/backend-py3.7/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 164, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "/root/.cache/pypoetry/virtualenvs/backend-py3.7/lib/python3.7/site-packages/django/db/models/fields/mixins.py", line 13, in get_cached_value
    return instance._state.fields_cache[cache_name]
KeyError: 'last_modified_by'
```